from typing import Literal, get_args

PRE_PUSH_SCRIPT_PATH = "pre_push.sh"
PRE_PUSH_HOOK_PATH = ".git/hooks/pre-push"
PRE_PUSH_BASE_SCRIPT = """#!/bin/bash
# This script is automatically generated by {TODO}
sh ../../pre-push.sh
"""
TYPING_LANGUAGES = Literal["Python", "Javascript", "Typescript", "Go"]
LANGUAGES = get_args(TYPING_LANGUAGES)

SHELL_INTERPRETER = "#!/bin/sh"
GENERATED_WARNING = "# This file is automatically generated by {TODO}"
DEFAULT_SCRIPT_BEGIN = f"""{SHELL_INTERPRETER}

{GENERATED_WARNING}"""

DEFAULT_SCRIPTS = {
    "Python": f"""{DEFAULT_SCRIPT_BEGIN}
# Lint
poetry run flake8 ./core
poetry run flake8 ./main.py
# Errors
poetry run mypy ./core
poetry run mypy ./main.py
# Dependencies
poetry check
# Tests 
poetry run pytest ./test/pre_push.py 
{GENERATED_WARNING}""",
    "Javascript": f"""{DEFAULT_SCRIPT_BEGIN}
npm run format
git add .
git commit -m "Code autoformatted"

npm run lint
npm run test

{GENERATED_WARNING}""",
    "Typescript": f"""{DEFAULT_SCRIPT_BEGIN}
npm run format
git add .
git commit -m "Code autoformatted"

npm run lint
npm run build
npm outdated
npm run test
{GENERATED_WARNING}""",
    "Go": f"""{DEFAULT_SCRIPT_BEGIN}
go vet ./...
staticcheck ./...
gosec ./...
go test -run pre_commit_test.go
{GENERATED_WARNING}""",
}
