from typing import Literal, get_args

PRE_PUSH_SCRIPT_PATH = "pre_push.sh"
PRE_PUSH_HOOK_PATH = ".git/hooks/pre-push"
PRE_PUSH_BASE_SCRIPT = """#!/bin/bash
# This script is automatically generated by {TODO}
sh ../../pre-push.sh
"""
TYPING_LANGUAGES = Literal["Python", "Javascript", "Typescript", "Go"]
LANGUAGES = get_args(TYPING_LANGUAGES)

SHELL_INTERPRETER = "#!/bin/sh"
GENERATED_WARNING = "# This file is automatically generated by {TODO}"
DEFAULT_SCRIPT_BEGIN = f"""{SHELL_INTERPRETER}

{GENERATED_WARNING}"""

DEFAULT_SCRIPTS = {
    "Python": f"""{DEFAULT_SCRIPT_BEGIN}

{GENERATED_WARNING}""",
    "Javascript": f"""{DEFAULT_SCRIPT_BEGIN}

{GENERATED_WARNING}""",
    "Typescript": f"""{DEFAULT_SCRIPT_BEGIN}

{GENERATED_WARNING}""",
    "Go": f"""{DEFAULT_SCRIPT_BEGIN}

{GENERATED_WARNING}""",
}